#! /bin/sh

export QT_QPA_PLATFORMTHEME="qt5ct"
export QT_QPA_PLATFORM="wayland"
export BEMENU_BACKEND="wayland"
export MOZ_ENABLE_WAYLAND=1
#export GTK_CSD=0
#export LD_PRELOAD="/lib/libgtk3-nocsd.so.0"

bemenu-run -i -p 'bemenu-run -▶' --tb '#323232' --hb '#323232' --fb '#323232' --nb '#323232' --fn 'Monofur Nerd Font 11.5' --tf '#44ffff' --hf '#44ffff' --sf '#44ffff' --scf '#44ffff'
