#!/bin/sh

#swaybg --image /home/fabiosantos/Pictures/Wallpapers/space_46-wallpaper-1366x768.jpg --mode fill
#swaybg --image /home/fabiosantos/Pictures/Wallpapers/beautiful_island_4-wallpaper-1366x768.jpg --mode fill
#swaybg --image /home/fabiosantos/Pictures/Wallpapers/434694.jpg --mode fill
#swaybg --image /home/fabiosantos/Pictures/Wallpapers/land_s_end-wallpaper-1366x768.jpg --mode fill
#swaybg --image /usr/share/backgrounds/sway/Sway_Wallpaper_Blue_1366x768.png --mode fill
#swaybg --image /home/fabiosantos/Pictures/Wallpapers/void-linux.png --mode fill
#swaybg --image /home/fabiosantos/Pictures/Wallpapers/CyborgGirl.jpg --mode fill
#swaybg --image /home/fabiosantos/Pictures/Wallpapers/04aadc7e90b47856650e2a412596fef0.jpg --mode fill
swaybg --image /home/fabiosantos/Pictures/Wallpapers/amazing_mountain_milky_way_by_yakub_nihat-wallpaper-1366x768.jpg --mode fill
#swaybg --image /home/fabiosantos/Pictures/Wallpapers/880619-1280x1024-hd-wallpaper-1920x1080-for-windows-7.jpg --mode fill
#swaybg --image /home/fabiosantos/Pictures/Wallpapers/258345.jpg --mode fill
