#!/bin/sh

# File preview handler for lf.

preview() {
    FILE_PATH="$1"
    X=$4
    Y=$5
    MW=$(($2-1))
    MH=$3
    ueberzugpp cmd -s $UB_SOCKET -a add -i PREVIEW -x $X -y $Y --max-width $MW --max-height $MH -f "$FILE_PATH"
    exit 1
}

case "$(file --dereference --brief --mime-type -- "$1")" in
        application/gzip | application/x-xz | application/x-bzip2 | application/x-lzma | application/x-tar)
                gtar tf "$1" ;;
        application/zip | application/x-rar)
                unzip -l "$1" ;;
        application/x-7z-compressed)
                7z l "$1" ;;
        *opendocument*)
                odt2txt "$1" ;;
        text/troff)
                man ./ "$1" | col -b ;;
        *torrent)
                aria2c --show-files "$1" ;;
        video/*)
                CACHE="$XDG_CACHE_HOME/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"
                [ ! -f "$CACHE" ] && ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0
                preview "$CACHE" "$2" "$3" "$4" "$5"
                ;;
        */pdf)
                CACHE="$XDG_CACHE_HOME/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"
                [ ! -f "$CACHE.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
                preview "$CACHE.jpg" "$2" "$3" "$4" "$5"
                ;;
        */postscript)
                CACHE="$XDG_CACHE_HOME/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"
                [ ! -f "$CACHE" ] && gs -o "$CACHE" -sDEVICE=pngalpha -dLastPage=1 "$1" >/dev/null
                preview "$CACHE" "$2" "$3" "$4" "$5"
                ;;
        image/svg+xml)
                CACHE="$XDG_CACHE_HOME/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"
                [ ! -f "$CACHE.jpg" ] && convert "$1" "$CACHE.jpg"
                preview "$CACHE.jpg" "$2" "$3" "$4" "$5"
                ;;
        image/*)
                preview "$1" "$2" "$3" "$4" "$5" ;;
        audio/*)
                exiftool "$1" ;;
        text/html)
                elinks -dump -dump-charset utf-8 "$1" ;;
        text/* | */xml | application/vnd.gentoo.* | application/json)
                clp "$1" || cat "$1" ;;
        application/pgp-encrypted)
                gpg -d -- "$1" ;;
        *)
                file --dereference --brief --mime-type -- "$1" ;;
esac
exit 0
