#!/bin/sh

# File preview handler for lf.

set -C -f
IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}"

preview() {
	if [ -f "$1" ] && [ -n "$DISPLAY" ] && [ "$USER" != "root" ] && command -V ueberzug >/dev/null 2>&1; then
		printf '{"action": "add", "identifier": "PREVIEW", "x": "%s", "y": "%s", "width": "%s", "height": "%s", "scaler": "contain", "path": "%s"}\n' "$4" "$5" "$(($2-1))" "$(($3-1))" "$1" > "$FIFO_UEBERZUG"
	else
		chafa "$1" -s "$4x"
	fi
}

ifub() {
	[ -n "$DISPLAY" ] && command -V ueberzug >/dev/null 2>&1
}

# Settings for highlight
HIGHLIGHT_FORMAT="truecolor"
HIGHLIGHT_STYLE='base16/xcode-dusk'
HIGHLIGHT_SIZE_MAX=262143  # 256KiB
HIGHLIGHT_TABWIDTH=8


case "$(file --dereference --brief --mime-type -- "$1")" in
        application/gzip | application/x-xz | application/x-bzip2 | application/x-lzma | application/x-tar)
                gtar tf "$1" ;;
        application/zip)
                unzip -l "$1" ;;
        application/x-rar)
                unrar l "$1" ;;
        application/x-7z-compressed)
                7z l "$1" ;;
        *opendocument*)
                odt2txt "$1" ;;
        text/troff)
                man ./ "$1" | col -b ;;
        *torrent)
                aria2c --show-files "$1" ;;
        video/*)
                CACHE="$XDG_CACHE_HOME/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"
                [ ! -f "$CACHE" ] && ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0
                preview "$CACHE" "$2" "$3" "$4" "$5" "$1"
                ;;
        */pdf)
                CACHE="$XDG_CACHE_HOME/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"
                [ ! -f "$CACHE.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
                preview "$CACHE.jpg" "$2" "$3" "$4" "$5" "$1"
                ;;
        */postscript)
                CACHE="$XDG_CACHE_HOME/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"
                [ ! -f "$CACHE" ] && gs -o "$CACHE" -sDEVICE=pngalpha -dLastPage=1 "$1" >/dev/null
                preview "$CACHE" "$2" "$3" "$4" "$5" "$1"
                ;;
        image/svg+xml)
                CACHE="$XDG_CACHE_HOME/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"
                [ ! -f "$CACHE.jpg" ] && magick "$1" "$CACHE.jpg"
                preview "$CACHE.jpg" "$2" "$3" "$4" "$5" "$1"
                ;;
        image/*)
	        preview "$1" "$2" "$3" "$4" "$5" "$1" ;;
        audio/*)
                mediainfo "$1" ;;
        text/html)
                lynx -width="$4" -display_charset=utf-8 -dump "$1" ;;
        text/* | */xml)
                highlight --replace-tabs="${HIGHLIGHT_TABWIDTH}" --out-format="${HIGHLIGHT_FORMAT}" --style="${HIGHLIGHT_STYLE}" \
                        --max-size="${HIGHLIGHT_SIZE_MAX}" --force -- "$1" || cat "$1" ;;
        application/pgp-encrypted)
                gpg -d -- "$1" ;;
        *)
                file --dereference --brief --mime-type -- "$1" ;;
esac
exit 1
