" {{{Make vim respects XDG specification
set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after
set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after
let g:netrw_home = $XDG_DATA_HOME."/vim"
call mkdir($XDG_DATA_HOME."/vim/spell", 'p')
set viewdir=$XDG_DATA_HOME/vim/view | call mkdir(&viewdir, 'p')
set backupdir=$XDG_CACHE_HOME/vim/backup | call mkdir(&backupdir, 'p')
set directory=$XDG_CACHE_HOME/vim/swap   | call mkdir(&directory, 'p')
set undodir=$XDG_CACHE_HOME/vim/undo     | call mkdir(&undodir,   'p')
set viminfofile=$XDG_CACHE_HOME/vim/viminfo
" }}}

" {{{Call plugins with vim-plug
call plug#begin('/home/fabiosantos/.local/share/vim/plugged')
Plug 'jalvesaq/Nvim-R'
Plug 'matze/vim-tex-fold'
call plug#end()

" Nvim-R
let R_rconsole_width = 0              " Always prefer a horizontal split for R console
let R_rconsole_height = 15            " Number of lines of R console
" }}}

" {{{General VIM Settings
" Change cursor shape in diferent modes
let &t_SI = "\<esc>[6 q"
let &t_EI = "\<esc>[2 q"
if exists('&t_SR')
    let &t_SR = "\<esc>[4 q"
endif

set timeout timeoutlen=1000 ttimeoutlen=100

" Disables automatic commenting on newline:
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" Toogle spellchecking
nnoremap <silent> <F11> :set spell!<cr>

" Enable filetype plugins
filetype plugin on
filetype indent on

" Compile document, be it groff/LaTeX/markdown/etc.
map <F5> :w! \| !compiler "<c-r>%"<CR>

" Render documents with Rmarkdown
autocmd filetype rmd map <F5> :!echo<space>"require(rmarkdown);<space>render('<c-r>%')"<space>\|<space>R<space>--vanilla<enter>
autocmd filetype rmd inoremap ;r ```{r<space>echo=TRUE}<CR>```<CR><CR><esc>2kO

" Open corresponding .pdf/.html or preview
map <F6> :!opout <c-r>%<CR><CR>

" Open netrw file explorer
map <C-n> :Explore<CR>

" Set a Local Leader
let mapleader = ","
let g:mapleader = ","

" Buffers & Navigation
nmap <leader>T :enew<cr>                " To open a new empty buffer
nmap <leader>l :bnext<CR>               " Move to the next buffer
nmap <leader>h :bprevious<CR>           " Move to the previous buffer
nmap <leader>bq :bp <BAR> bd #<CR>      " Close the current buffer and move to the previous one
nmap <leader>bl :ls<CR>                 " Show all open buffers and their status

" Use wildmenu for navigate between buffers
set wildchar=<Tab> wildmenu wildmode=full
set wildcharm=<C-Z>
nnoremap <Tab> :b <C-Z>

" Tabs & Navigation
map <leader>nt :tabnew<cr>      " To create a new tab.
map <leader>to :tabonly<cr>     " To close all other tabs (show only the current tab).
map <leader>tc :tabclose<cr>    " To close the current tab.
map <leader>tm :tabmove<cr>     " To move the current tab to next position.
map <leader>tn :tabn<cr>        " To swtich to next tab.
map <leader>tp :tabp<cr>        " To switch to previous tab.

" Splits & Tabbed Files
set splitbelow splitright
" Remap splits navigation to just CTRL + hjkl
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Change 2 split windows from vert to horiz or horiz to vert
map <Leader>th <C-w>t<C-w>H
map <Leader>tk <C-w>t<C-w>K

" Line Numbers & Indentation
set backspace=indent,eol,start  " To make backscape work in all conditions.
set display+=lastline           " Prevente vim show '@' if the line dont fit the screen
set showbreak=﬌                 " Character to show before the lines that have been soft-wrapped
set ma                          " To set mark a at current cursor location.
set number relativenumber       " To switch the line numbers on.
set autoindent                  " To copy indentation from current line when starting a new line.
set si                          " To switch on smart indentation.

" General tab settings
set smarttab                    " To use smart tabs.
set tabstop=4                   " number of visual spaces per TAB
set softtabstop=4               " number of spaces in tab when editing
set shiftwidth=4                " number of spaces to use for autoindent
set expandtab                   " expand tab to spaces so that tabs are spaces

" Search
set ignorecase                  " To ignore case when searching.
set smartcase                   " When searching try to be smart about cases.
set incsearch                   " To make search act like search in modern browsers.
set magic                       " For regular expressions turn magic on.

" Brackets
set showmatch                   " To show matching brackets when text indicator 
                                " is over them.
set mat=2                       " How many tenths of a second to blink 
                                " when matching brackets.

" Errors
set noerrorbells                " No annoying sound on errors.

" Color & Fonts
syntax enable                   " Enable syntax highlighting.
language en_US.utf-8            " Use English as default
set encoding=utf8               " Set utf8 as standard encoding and 
set spelllang=en,pt             " Set standard languages.
set t_Co=256                    " Enable 256 colors palette"

" Files & Backup
set nobackup                    " Turn off backup.
set nowb                        " Don't backup before overwriting a file.
set noswapfile                  " Don't create a swap file.
set ffs=unix,dos,mac            " Use Unix as the standard file type.

" Misc
set mouse=a                     " Enable mouse support    
set ttymouse=sgr                " Fixes mouse scrolling in st
set clipboard=unnamedplus       " Vim clipboard buffer shared with the system clipboard
set laststatus=2                " Always show statusline
set wildmenu                    " Vim autocompetion menu
set hidden                      " Allows buffers to be hidden
" }}}

" {{{Colors and Theming
highlight LineNr           ctermfg=8    ctermbg=none    cterm=none
highlight CursorLineNr     ctermfg=7    ctermbg=8       cterm=none
highlight VertSplit        ctermfg=0    ctermbg=8       cterm=none
highlight Statement        ctermfg=2    ctermbg=none    cterm=none
highlight Directory        ctermfg=4    ctermbg=none    cterm=none
highlight StatusLine       ctermfg=7    ctermbg=0       cterm=none
highlight StatusLineNC     ctermfg=7    ctermbg=none    cterm=none
highlight Comment          ctermfg=103  ctermbg=none    cterm=italic
highlight Constant         ctermfg=12   ctermbg=none    cterm=none
highlight Special          ctermfg=4    ctermbg=none    cterm=none
highlight Identifier       ctermfg=6    ctermbg=none    cterm=bold
highlight PreProc          ctermfg=5    ctermbg=none    cterm=none
highlight String           ctermfg=12   ctermbg=none    cterm=none
highlight Number           ctermfg=1    ctermbg=none    cterm=none
highlight Function         ctermfg=1    ctermbg=none    cterm=bold
highlight WildMenu         ctermfg=0       ctermbg=4       cterm=none
highlight Folded           ctermfg=103     ctermbg=234     cterm=none
highlight FoldColumn       ctermfg=103     ctermbg=234     cterm=none
highlight DiffAdd          ctermfg=none    ctermbg=23      cterm=none
highlight DiffChange       ctermfg=none    ctermbg=56      cterm=none
highlight DiffDelete       ctermfg=168     ctermbg=96      cterm=none
highlight DiffText         ctermfg=0       ctermbg=80      cterm=none
highlight SignColumn       ctermfg=244     ctermbg=235     cterm=none
highlight Conceal          ctermfg=251     ctermbg=none    cterm=none
highlight SpellBad         ctermfg=168     ctermbg=none    cterm=underline
highlight SpellCap         ctermfg=80      ctermbg=none    cterm=underline
highlight SpellRare        ctermfg=121     ctermbg=none    cterm=underline
highlight SpellLocal       ctermfg=186     ctermbg=none    cterm=underline
highlight Pmenu            ctermfg=251     ctermbg=234     cterm=none
highlight PmenuSel         ctermfg=0       ctermbg=111     cterm=none
highlight PmenuSbar        ctermfg=206     ctermbg=235     cterm=none
highlight PmenuThumb       ctermfg=235     ctermbg=206     cterm=none
highlight TabLine          ctermfg=244     ctermbg=234     cterm=none
highlight TablineSel       ctermfg=0       ctermbg=247     cterm=none
highlight TablineFill      ctermfg=244     ctermbg=234     cterm=none
highlight CursorColumn     ctermfg=none    ctermbg=236     cterm=none
highlight CursorLine       ctermfg=none    ctermbg=236     cterm=none
highlight ColorColumn      ctermfg=none    ctermbg=236     cterm=none
highlight Cursor           ctermfg=0       ctermbg=5       cterm=none
highlight htmlEndTag       ctermfg=114     ctermbg=none    cterm=none
highlight xmlEndTag        ctermfg=114     ctermbg=none    cterm=none
" }}}

" {{{Statusline settings
set statusline=
set statusline+=\ %{toupper(g:currentmode[mode()])}              " Show current mode
set statusline+=%{&spell?'[SPELL]':''}                           " Show if spellchecking is active
set statusline+=\ %F                                             " Full path to the file in the buffer
set statusline+=%{&modified?'\ [+]':''}                          " Show if file is modified
set statusline+=%{&readonly?'\ []':''}                          " Show if file is readonly
set statusline+=%<                                               " Truncate line here
set statusline+=%=                                               " Separation point between left and right aligned items.
set statusline+=%{&filetype!=#''?&filetype.'\ ':'none\ '}        " Filetype
set statusline+=%{&fileencoding!='utf-8'?''.&fileencoding.'':''} " Encoding
set statusline+=%-7([%{&fileformat}]%)                           " Fileformat
set statusline+=[%l/%L]                                          " Location of cursor line

" Vim current mode
let g:currentmode={
       \ 'n'  : 'NORMAL ',
       \ 'v'  : 'VISUAL ',
       \ 'V'  : 'V·Line ',
       \ "\<C-V>" : 'V·Block ',
       \ 'i'  : 'INSERT ',
       \ 'R'  : 'R ',
       \ 'Rv' : 'V·Replace ',
       \ 'c'  : 'Command ',
       \ 't'  : 'console',
       \}

" }}}
