#!/bin/sh

case $BLOCK_BUTTON in
	1) amixer -q set Master toggle && pkill -RTMIN+10 dwmblocks ;;
	2) "$TERMINAL" -e "$EDITOR" "$0" ;;
	3) "$TERMINAL" -e alsamixer ;;
esac

volume="$(amixer sget Master | awk -F"[][]" '/dB/ { print $2 }' | sed 's/%//')"
headphone="$(cat '/proc/asound/card0/codec#0' | grep "Pin-ctls" | awk 'NR==2{print $3}')"

[ $(amixer sget Master | awk 'NR==5{print $6}') = "[off]" ] && echo "  Muted" && exit

case 1 in
	$((volume >= 70)) ) icon="" ;;
	$((volume >= 30)) ) icon="" ;;
	$((volume >= 1)) ) icon="" ;;
	$((volume == 0)) ) icon="" ;;
esac

[ "$headphone" != "OUT" ] && icon=""

echo "$icon $volume%"
