#!/bin/sh

BATTERY=$(cat /sys/class/power_supply/BAT1/capacity)
STATUS=$(cat /sys/class/power_supply/BAT1/status)

BATTERY_INFO=" $BATTERY%"

[ "$STATUS" = "Charging" ] && BATTERY_INFO=" $BATTERY%"

[ "$STATUS" = "Full" ] && BATTERY_INFO=" $BATTERY%"

# Low Battery warning
[ "$BATTERY" = "10" ] && notify-send "    Low Battery 10%" --icon=battery-caution

echo "$BATTERY_INFO"
