#!/bin/sh

case $BLOCK_BUTTON in
	2) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

battery=$(cat /sys/class/power_supply/BAT1/capacity)
status=$(cat /sys/class/power_supply/BAT1/status)

[ $status = "Discharging" ] && battery_INFO=" $battery%"
[ $status = "Charging" ] && battery_INFO=" $battery%"
[ $status = "Full" ] && battery_INFO=" $battery%"
[ $status = "Unknown" ] && battery_INFO=" $battery%"
[ $status = "Not charging" ] && battery_INFO=" $battery%"

# Low Battery warning
[ "$battery" = "10" ] && notify-send "    Low Battery 10%"

echo "$battery_INFO"
