#!/bin/sh

INFO=$(acpi -b | sed -rn 's/^.*, (.*?)%, ((.*?):[0-9]{2} )?(.*)$/\1 \3 \4/p')
BATTERY=$(echo ${INFO%% *})

BATTERY_INFO=" $BATTERY%"

[ "$(echo $INFO | grep charg)" ] && BATTERY_INFO=" $BATTERY%"

[ ! "$BATTERY" ] && BATTERY_INFO=" 100%"

# Low Battery warning
[ "$BATTERY" = "10" ] && notify-send "     Low Battery 10%" --icon=battery-caution

echo "$BATTERY_INFO"
