#!/bin/sh

BRIGHTNESS="$(xbacklight -get)"

if [ $BRIGHTNESS -lt 20 ]; then
        BRIGHTNESS_ICON="🌕"
elif [ $BRIGHTNESS -lt 40 ]; then
        BRIGHTNESS_ICON="🌖"
elif [ $BRIGHTNESS -lt 60 ]; then
        BRIGHTNESS_ICON="🌗"
elif [ $BRIGHTNESS -lt 80 ]; then
        BRIGHTNESS_ICON="🌘"
else
        BRIGHTNESS_ICON="🌑"
fi

echo "$BRIGHTNESS_ICON $BRIGHTNESS%"
