#!/bin/sh

artist=$(cmus-remote -Q 2> /dev/null | grep 'tag artist' | cut -d ' ' -f 3-)
title=$(cmus-remote -Q 2> /dev/null | grep 'tag title' | cut -d ' ' -f 3-)
status=$(cmus-remote -Q 2> /dev/null | awk NR==1'{print $2}')

out="  $artist - $title"

[ ! $status ] && out="  off"
[ $status = "stopped" ] 2> /dev/null && out=" ■ Stopped"
[ $status = "paused" ] 2> /dev/null && out="  $artist - $title"

echo "$out"
