#!/bin/sh

case $BLOCK_BUTTON in
	1) notify-send "$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)" ;;
	2) "$TERMINAL" -e "$EDITOR" "$0" ;;
	3) "$TERMINAL" -e htop ;;
esac

cpu="$(top -bn1 | grep "%Cpu(s)" | awk '{printf "%.2f\n", $(2)}')"

echo "﬙ $cpu%"
