#!/bin/sh

case $BLOCK_BUTTON in
	1) "$TERMINAL" -e mutt && pkill -RTMIN+11 dwmblocks ;;
	2) "$TERMINAL" -e "$EDITOR" "$0" ;;
	3) mpop fabioesantos@ufmg.br >/dev/null ;;
esac

unread="$(find $XDG_DATA_HOME/mail/*/[Ii][Nn][Bb][Oo][Xx]/new/* -type f 2>/dev/null | wc -l)"

[ $(pidof mbsync) ] && icon=" ﮮ"

[ $(pidof mpop) ] && icon=" ﮮ"

echo " $unread$icon"
