#!/bin/sh

case $BLOCK_BUTTON in
	1) mpc toggle ;;
	2) "$TERMINAL" -e "$EDITOR" "$0" ;;
	3) "$TERMINAL" -e ncmpcpp ;;
esac

mpid="$(pidof mpd)"

[ "$mpid" ] &&
        info="$(mpc current)" &&
        music="$(mpc | awk 'NR==2{print $3}')" &&
        mpdstate="$(mpc | awk -F"[][]" 'NR==2{print $2}')"

[ -z "$music" ] && STATUS="■ Stopped"

[ -z "$mpid" ] && STATUS="  MPD off"

[ "$mpdstate" = "paused" ] && STATUS=" $info ($music)"

[ "$mpdstate" = "playing" ] && STATUS=" $info ($music)"

echo " $STATUS"
