#!/bin/sh

MPID="$(pidof mpd)"

[ "$MPID" ] &&
        INFO="$(mpc | sed 1q)" &&
        MUSIC="$(mpc | awk 'NR==2{print $3}')"

if [ -z "$MPID" ]; then
        STATUS="ﳤ  MPD Disconnected"
elif [ -z "$MUSIC" ]; then
        STATUS="◼ Stopped"
else
        STATUS="🎵 $INFO ($MUSIC)"
fi

echo " $STATUS"
