#!/bin/sh

network=$(ip route get 1.1.1.1 | grep -Po '(?<=dev\s)\w+') 2>/dev/null
network_active=" "

[ $network = "wlan0" ] && network_active=" "

[ $network = "eth0" ] && network_active=" "

update() {
    sum=0
    for arg; do
        read -r i < "$arg"
        sum=$(( sum + i ))
    done
    cache=$XDG_CACHE_HOME/nettraf/${1##*/}
    [ -f "$cache" ] && read -r old < "$cache" || old=0
    printf %d\\n "$sum" > "$cache"
    printf %d\\n $(( sum - old ))
}

rx=$(update /sys/class/net/[ew]*/statistics/rx_bytes)
tx=$(update /sys/class/net/[ew]*/statistics/tx_bytes)

if [ ! $network ]; then
        echo "$network_active Disconnected"
else
        printf "$network_active %4sB %4sB\\n" $(numfmt --to=iec $rx) $(numfmt --to=iec $tx)
fi
