#!/bin/sh

network=$(ip route get 1.1.1.1 | grep -Po '(?<=dev\s)\w+')
#interface_easyname=$(dmesg | grep $network | grep renamed | awk 'NF>1{print $NF}')
#ping="("$(ping -c 1 1.1.1.1 | tail -1 | awk '{print $4}' | cut -d '/' -f 2 | cut -d '.' -f 1)" ms)"

if ! [ "$network" ]; then
        network_active="⛔"
        network="Disconnected"
elif [ "$network" = "wlp2s0" ]; then
        network_active=" "
elif [ "$network" = "tun0" ]; then
        network_active="😎"
        interface_easyname="$network"
else
        network_active=""
fi

echo "$network_active $network"
