#!/bin/sh

network=$(ip route get 1.1.1.1 | grep -Po '(?<=dev\s)\w+') 2>/dev/null
network_active=" "

[ $network = "wlan0" ] && network_active=" "

[ $network = "eth0" ] && network_active=" "

[ $network = "usb0" ] && network_active=" "


ping=$(ping -c 1 www.google.com | tail -1| awk '{print $4}' | cut -d '/' -f 2 | cut -d '.' -f 1)ms


if [ ! $network ]; then
        echo "$network_active Disconnected"
else
        echo "$network_active $network $ping"
fi
