#!/bin/sh

transmission-remote -l | grep % |
	sed " # The letters are for sorting and will not appear.
	s/.*Stopped.*/A 🛑/;
	s/.*Seeding.*/Z 🌱/;
	s/.*100%.*/N ✅/;
	s/.*Idle.*/B 🕰️/;
	s/.*Uploading.*/L ﰵ/;
	s/.*%.*/M ﰬ/" |
		sort -h | uniq -c | awk '{print $3 $1}' | paste -sd ' ' -

