#!/bin/sh
############################################################
# File:     xinitrc   Xorg init config file                #
# URL:      https://github.com/fabioesantos/Dotfiles       #
# Author:   Fabio Santos <fabiosantos.bio@protonmail.com>  #
############################################################
#                 _       _ _
#           __  _(_)_ __ (_) |_ _ __ ___
#           \ \/ / | '_ \| | __| '__/ __|
#            >  <| | | | | | |_| | | (__
#           /_/\_\_|_| |_|_|\__|_|  \___|
#
#
# redirect errors to a file in user's home directory
for errfile in "$XDG_CACHE_HOME/X11/xsession-errors"
do
	if ( cp /dev/null "$errfile" 2> /dev/null )
	then
		chmod 600 "$errfile"
		exec > "$errfile" 2>&1
		break
	fi
done

userprofile="$XDG_CONFIG_HOME/X11/xprofile"
userresources="$XDG_CONFIG_HOME/X11/Xresources"

[ -f $userprofile ] && . $userprofile
[ -f $userresources ] && xrdb -load $userresources
 
# Start session in XSESSION variable or xsession file
[ $XSESSION ] && exec $XSESSION
[ -f $XDG_CONFIG_HOME/X11/xsession ] && . $XDG_CONFIG_HOME/X11/xsession
