#!/bin/sh

# Starting some nice programs...
# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

[ ! -e $XDG_RUNTIME_DIR/xobpipe ] && mkfifo $XDG_RUNTIME_DIR/xobpipe

/usr/bin/numlockx on &

xwallpaper --stretch $XDG_CONFIG_HOME/X11/wall.jpg &

$COMPOSITOR &

dwmblocks &

#xss-lock slock &

redshift 1>/dev/null 2>/dev/null &

xvattr -a XV_SYNC_TO_VBLANK -v 0 >/dev/null &

tail -f $XDG_RUNTIME_DIR/xobpipe | xob >/dev/null &
