#!/bin/sh

# Starting some nice programs...
# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

#xrandr --output HDMI1 --mode 1360x768 --output eDP1 --off &

/usr/bin/numlockx on &

xwallpaper --stretch $XDG_CONFIG_HOME/X11/wall.jpg &

if [ ! $(pidof redshift) ]; then
        redshift 1>/dev/null 2>/dev/null &
else
        killall redshift && redshift 1>/dev/null 2>/dev/null &
fi

picom -c --backend glx --vsync &

dwmblocks 2>/dev/null &

urxvtd -q -o &

xss-lock -l xlock 2>/dev/null &
