#! /bin/sh
#
######################################################
#  ____ ____  ______        ____  __ ____   ____ 
# | __ ) ___||  _ \ \      / /  \/  |  _ \ / ___|
# |  _ \___ \| |_) \ \ /\ / /| |\/| | |_) | |    
# | |_) |__) |  __/ \ V  V / | |  | |  _ <| |___ 
# |____/____/|_|     \_/\_/  |_|  |_|_| \_\\____|
######################################################
#
# A customized bspwmrc for the bspwm window manager.
# https://github.com/baskerville/sxhkd
# https://github.com/baskerville/bspwm

#### AUTOSTART ####
pgrep -x sxhkd > /dev/null || sxhkd &
sh $HOME/.config/polybar/launch.sh &
urxvtd -q -f -o &
[ ! "$(pidof conky)" ] && conky --config="$XDG_CONFIG_HOME/conky/conkyrc" &
killall dwmstatus &

#### MONITORS ####
bspc monitor eDP1 -d I II III IV V VI VII VIII IX

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  3
bspc config window_gap                    7
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_follows_pointer         true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#4a464d"
bspc config active_border_color	              "#504477"
bspc config focused_border_color	      "#796af5"
bspc config presel_feedback_color	      "#5e81ac"

### Window's rules
bspc rule -a Zathura state=tiled
bspc rule -a Surf state=tiled
