#! /bin/sh
#
######################################################
#  ____ ____  ______        ____  __ ____   ____ 
# | __ ) ___||  _ \ \      / /  \/  |  _ \ / ___|
# |  _ \___ \| |_) \ \ /\ / /| |\/| | |_) | |    
# | |_) |__) |  __/ \ V  V / | |  | |  _ <| |___ 
# |____/____/|_|     \_/\_/  |_|  |_|_| \_\\____|
######################################################
#
# A customized bspwmrc for the bspwm window manager.
# https://github.com/baskerville/sxhkd
# https://github.com/baskerville/bspwm

#### AUTOSTART ####
bspwmbar &
pgrep -x sxhkd > /dev/null || sxhkd &
#bash /home/fabiosantos/.config/polybar/launch.sh --shades
#sh $HOME/.config/polybar/launch.sh &
#xcompmgr -c -C -t-5 -l-5 -r4.2 -o.55 &
#[ ! "$(pidof conky)" ] && conky --config="$XDG_CONFIG_HOME/conky/conkyrc" &
#bar_lemon | lemonbar -f "Monofur Nerd Font:size=10" &
killall dwmblocks &

#### MONITORS ####
bspc monitor HDMI1 -d 1 2 3 4 5 6 7 8 9

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  3
bspc config window_gap                    4
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#4a464d"
bspc config active_border_color	              "#504477"
bspc config focused_border_color	      "#796af5"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)

bspc rule -a Zathura state=tiled
bspc rule -a Surf state=tiled
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
