#!/bin/ksh

# Source .profile in every new shell.
. ~/.profile

# Source some aliases.
[ -f "$XDG_CONFIG_HOME/aliasrc" ] && . $XDG_CONFIG_HOME/aliasrc

# Source colors for PS1 and ls command.
[ -f "$XDG_CONFIG_HOME/shell_cols" ] && . $XDG_CONFIG_HOME/shell_cols
[ -f "$XDG_CONFIG_HOME/ls_colorsrc" ] && . $XDG_CONFIG_HOME/ls_colorsrc

# Source completions.
[ -f "$XDG_DATA_HOME/ksh/completions" ] && . $XDG_DATA_HOME/ksh/completions

# Enable emacs mode.
set -o emacs

# Bind keys.
bind '^[[A'=up-history
bind '^[[B'=down-history
bind '^[[C'=forward-char
bind '^[[D'=backward-char
bind -m '^A'='meh *^J'
bind -m '^O'='lfcd^J'

# History settings.
HISTFILE="$XDG_CACHE_HOME/ksh/history"
HISTSIZE=1000000
HISTCONTROL=ignoredups:ignorespace

# set prompt.
if [[ "$USER" = "root" ]]; then
        PS1="${BBLUE}\u${RESET}@\H ${BLUE}\W${RESET} # "
else
        PS1="${BBLUE}\u${RESET}@\H ${BLUE}\W${RESET} \$ "
fi

# Image previews in lf.
function lf {
	LF_TEMPDIR="$(mktemp -d -t lf-tempdir-XXXXXX)"
	LF_TEMPDIR="$LF_TEMPDIR" lf-run -last-dir-path="$LF_TEMPDIR/lastdir" "$@"
	if [[ "$(cat "$LF_TEMPDIR/cdtolastdir" 2>/dev/null)" -eq 1 ]]; then
		cd "$(cat "$LF_TEMPDIR/lastdir")"
	fi
	rm -r "$LF_TEMPDIR"
	unset LF_TEMPDIR
}

# Use lf to switch directories.
function lfcd {
    tmp="$(mktemp)"
    lf -single -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp" >/dev/null
        [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
    fi
}
